# Generated by Django 5.0.6 on 2025-02-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_lesson_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='author',
        ),
    ]
